spring.application.name=pevau

# H2
spring.datasource.url=jdbc:h2:file:./pevaudb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ddl
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=update
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/crear_esquema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=target/borrar_esquema.sql

# mostrar sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Esto se va a pushear al repo, pero bueno es el servidor de mocks asi que ¯\_(ツ)_/¯
external.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIkFETUlOSVNUUkFET1IiXSwic3ViIjoiMSIsImlhdCI6MTc3Nzc4ODc3NSwiZXhwIjoxODQwODYwNzc1fQ.QItS3nUduiC52ty2wx4MlZzTHq_N6t-QkFOg78sSdrFeWjhktrB6NCxq-CEuxIzRO9t8LItJMBK4bBXfrGzGfg